services:
    mysql:
        image: mysql:8.3
        container_name: mysql
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "user",
                    "-ppassword",
                ]
            interval: 10s
            timeout: 5s
            retries: 10

        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    app:
        build: ./
        container_name: app
        depends_on:
            mysql:
                condition: service_healthy # Wait for MySQL to be healthy
        restart: on-failure
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_NAME: db
            DB_USER: user
            DB_PASSWORD: password
        ports:
            - "8080:8080"
        command: ["tail", "-f", "/dev/null"]
    # apptests container for running tests
    # apptests:
    #     build: ./
    #     image: maven:3.9.6-eclipse-temurin-21
    #     container_name: apptests
    #     depends_on:
    #         mysql:
    #             condition: service_healthy # Wait for MySQL to be healthy
    #     restart: on-failure
    #     working_dir: /app # Maven seeks pom file at the project's root
    #     volumes:
    #         - ./:/app # Mount the current directory to /app in the container
    #     environment:
    #         DB_HOST: mysql
    #         DB_PORT: 3306
    #         DB_NAME: db
    #         DB_USER: user
    #         DB_PASSWORD: password
    #     ports:
    #         - "8080:8080"
    #     command: mvn test

    # mysql client container for testing
    mysql-client:
        image: mysql:8.3
        container_name: mysql-client
        depends_on:
            - mysql
        entrypoint: ["mysql", "-h", "mysql", "-u", "user", "-p", "password"]
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password

volumes:
    mysql_data:
